import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Handmatige sidebar, bewust niet autogenerated uit de mappenstructuur: dit
// bestand is de enige bron van volgorde, en de lesbestanden hebben geen
// sidebar_position. Elke categorie van de FastAPI-route heeft wel een eigen map
// in docs/FastAPI/ (eerste-server, html, …, afronden); src/data/mappen.test.ts
// eist dat de lessen van een categorie precies in één map staan. Een les
// verhuizen verandert zijn adres: zet het oude adres dan in
// src/data/omleidingen.ts, anders komt een bladwijzer op een 404 uit.
//
// De cheatsheet en de troubleshooting-pagina staan bewust in geen enkele
// sidebar: het zijn referentiepagina's, bereikbaar via de navbar. Projectstructuur
// ook niet; die is naslag en gelinkt vanuit de cheatsheet en de lessen. In de
// navbar paste hij niet meer: op 1280 breed liepen de items dan over twee regels.
// SqliteDict op een rij (FastAPI/sqlitedict/op-een-rij) is net zo naslag:
// gelinkt vanuit de cheatsheet en de drie lessen over SqliteDict.
const sidebars: SidebarsConfig = {
  // Eerst de startpagina: wat je aan het eind hebt, wat je al moet kunnen, en
  // de route als kaart (<Routekaart>, die deze sidebar zelf leest). De navbar-
  // link FastAPI komt daar uit.
  apiSidebar: [
    'FastAPI/index',
    {
      type: 'category',
      label: 'Je eerste server',
      items: [
        'FastAPI/eerste-server/installatie',
        'FastAPI/eerste-server/eerste_endpoint',
        'FastAPI/eerste-server/verzoek-eerste',
        'FastAPI/eerste-server/devtools-netwerk',
      ],
    },
    {
      type: 'category',
      label: "HTML-pagina's",
      items: [
        'FastAPI/html/html_tonen',
        'FastAPI/html/html_bestanden',
        'FastAPI/html/links',
        'FastAPI/html/static_files',
        'FastAPI/html/afbeeldingen',
        'FastAPI/html/verzoek-static',
      ],
    },
    {
      type: 'category',
      label: 'Templates en formulieren',
      items: [
        'FastAPI/formulieren/templates',
        'FastAPI/formulieren/get_vs_post',
        'FastAPI/formulieren/forms',
        'FastAPI/formulieren/post_met_templates',
      ],
    },
    {
      type: 'category',
      label: 'Gegevens opslaan (SqliteDict)',
      items: [
        'FastAPI/sqlitedict/database',
        'FastAPI/sqlitedict/database-sleutels',
        'FastAPI/sqlitedict/database-waarden',
      ],
    },
    {
      type: 'category',
      label: 'Opslaan en tonen in je server',
      items: [
        'FastAPI/gastenboek/post_naar_database',
        'FastAPI/gastenboek/lijst_tonen',
        'FastAPI/gastenboek/redirect',
        'FastAPI/gastenboek/detailpagina',
        'FastAPI/gastenboek/verzoek-get',
      ],
    },
    {
      type: 'category',
      label: 'Accounts',
      items: ['FastAPI/accounts/registreren', 'FastAPI/accounts/inloggen'],
    },
    {
      type: 'category',
      label: 'Uitbreiding: zonder herladen (htmx)',
      items: [
        'FastAPI/zonder-herladen/htmx',
        'FastAPI/zonder-herladen/htmx-overzicht',
        'FastAPI/zonder-herladen/verzoek-htmx',
      ],
    },
    {
      type: 'category',
      label: 'Uitbreiding: JavaScript in de browser',
      items: [
        'FastAPI/in-de-browser/javascript',
        'FastAPI/in-de-browser/devtools-console',
        'FastAPI/in-de-browser/server-of-browser',
      ],
    },
    {
      type: 'category',
      label: 'Uitbreiding: onthouden (cookies en sessies)',
      items: [
        'FastAPI/onthouden/cookies',
        'FastAPI/onthouden/sessies',
        'FastAPI/onthouden/cookie-of-sessie',
        'FastAPI/onthouden/verzoek-sessie',
      ],
    },
    {
      type: 'category',
      label: 'Afronden',
      // De eigen 404-pagina staat vooraan in Afronden: hij bouwt op Eén item
      // tonen en de templates uit de basis, heeft geen uitbreiding nodig, en
      // hoort bij het netjes maken voordat je de site in Laat het zien aan je
      // klas toont.
      items: [
        'FastAPI/afronden/foutpagina',
        'FastAPI/afronden/hoe-een-verzoek-werkt',
        'FastAPI/afronden/laat-het-zien',
      ],
    },
  ],
  // Eerst de startpagina (het ene idee, de spelregel, de statuscodes) en het
  // gereedschap (httpx). Dan per zwakheid een categorie met kleine lessen, van
  // makkelijk naar moeilijk: zichtbaar (wat je server laat zien, nog zonder
  // aanval), invoer, xss, dos, toegang, cookies, wachtwoorden.
  // DoS staat vroeg, want het is één decorator en een for-loop; Wachtwoorden
  // staat achteraan en gebruikt de limiet uit DoS. Ingeklapt, zodat de sidebar
  // een kaart blijft; Docusaurus klapt de reeks open waar de leerling in zit.
  veiligheidSidebar: [
    'veiligheid/index',
    'veiligheid/gereedschap',
    {
      type: 'category',
      label: 'Wat je server laat zien',
      collapsed: true,
      items: [
        'veiligheid/zichtbaar/handleiding',
        'veiligheid/zichtbaar/vergeten',
        'veiligheid/zichtbaar/uitzetten',
        'veiligheid/zichtbaar/bestanden',
        'veiligheid/zichtbaar/gitignore',
        'veiligheid/zichtbaar/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Invoer controleren',
      collapsed: true,
      items: [
        'veiligheid/invoer/maxlength',
        'veiligheid/invoer/grenzen',
        'veiligheid/invoer/fouten-lezen',
        'veiligheid/invoer/inhoud',
        'veiligheid/invoer/getallen',
        'veiligheid/invoer/paden',
        'veiligheid/invoer/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'HTML van een bezoeker (XSS)',
      collapsed: true,
      items: [
        'veiligheid/xss/zwakheid',
        'veiligheid/xss/escape',
        'veiligheid/xss/templates',
        'veiligheid/xss/safe',
        'veiligheid/xss/eigen-project',
        'veiligheid/xss/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Te veel verzoeken (DoS)',
      collapsed: true,
      items: [
        'veiligheid/dos/verzoek',
        'veiligheid/dos/dos-en-ddos',
        'veiligheid/dos/zelf-meten',
        'veiligheid/dos/limiet',
        'veiligheid/dos/te-veel',
        'veiligheid/dos/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Wie mag wat',
      collapsed: true,
      items: [
        'veiligheid/toegang/zwakheid',
        'veiligheid/toegang/controle',
        'veiligheid/toegang/server-weet',
        'veiligheid/toegang/elk-endpoint',
        'veiligheid/toegang/eigen-project',
        'veiligheid/toegang/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Cookies afschermen',
      collapsed: true,
      items: [
        'veiligheid/cookies/zwakheid',
        'veiligheid/cookies/httponly',
        'veiligheid/cookies/samesite',
        'veiligheid/cookies/uitloggen',
        'veiligheid/cookies/eigen-project',
        'veiligheid/cookies/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Wachtwoorden veilig opslaan',
      collapsed: true,
      items: [
        'veiligheid/wachtwoorden/gewone-tekst',
        'veiligheid/wachtwoorden/hash',
        'veiligheid/wachtwoorden/zout',
        'veiligheid/wachtwoorden/traag',
        'veiligheid/wachtwoorden/registreren',
        'veiligheid/wachtwoorden/inloggen',
        'veiligheid/wachtwoorden/wijzigen',
        'veiligheid/wachtwoorden/pogingen',
        'veiligheid/wachtwoorden/praktijk',
      ],
    },
    'veiligheid/eigen-project',
  ],
};

export default sidebars;
