import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Handmatige sidebar, bewust niet autogenerated uit de mappenstructuur: de
// lessen groeperen in zes blokken zónder de bestanden te verplaatsen, want
// verplaatsen verandert de URL's — en die staan in honderden interne links en
// in bookmarks van leerlingen. Dit bestand is daarmee de enige bron van
// volgorde; de lesbestanden hebben geen sidebar_position meer.
//
// De cheatsheet en de troubleshooting-pagina staan bewust in geen enkele
// sidebar: het zijn referentiepagina's, bereikbaar via de navbar.
const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: 'category',
      label: 'Starten',
      items: [
        'FastAPI/installatie',
        'FastAPI/eerste_endpoint',
        'FastAPI/verzoek-eerste',
        'FastAPI/devtools-netwerk',
      ],
    },
    {
      type: 'category',
      label: "Pagina's tonen",
      items: [
        'FastAPI/html_tonen',
        'FastAPI/static_files',
        'FastAPI/html_bestanden',
        'FastAPI/links',
        'FastAPI/afbeeldingen',
        'FastAPI/verzoek-static',
      ],
    },
    {
      type: 'category',
      label: 'Formulieren',
      items: ['FastAPI/get_vs_post', 'FastAPI/forms', 'FastAPI/post_met_templates'],
    },
    {
      type: 'category',
      label: 'Het gastenboek',
      items: [
        'FastAPI/database',
        'FastAPI/post_naar_database',
        'FastAPI/lijst_tonen',
        'FastAPI/redirect',
        'FastAPI/detailpagina',
        'FastAPI/verzoek-get',
        'FastAPI/verzoek-post',
      ],
    },
    {
      type: 'category',
      label: 'Zonder herladen',
      items: ['FastAPI/htmx', 'FastAPI/htmx-overzicht', 'FastAPI/verzoek-htmx'],
    },
    {
      type: 'category',
      label: 'In de browser',
      items: ['FastAPI/javascript', 'FastAPI/devtools-console', 'FastAPI/server-of-browser'],
    },
    {
      type: 'category',
      label: 'Onthouden',
      items: [
        'FastAPI/cookies',
        'FastAPI/sessies',
        'FastAPI/cookie-of-sessie',
        'FastAPI/verzoek-sessie',
      ],
    },
    {
      type: 'category',
      label: 'Afronden',
      items: [
        'FastAPI/hoe-een-verzoek-werkt',
        'FastAPI/laat-het-zien',
        'FastAPI/jouw-project',
        'FastAPI/projectstructuur',
      ],
    },
  ],
  // Per zwakheid een categorie met drie stappen: de zwakheid (zelf nadoen, op
  // je eigen server), de oplossing, en wat er in de praktijk nog gebeurt.
  veiligheidSidebar: [
    {
      type: 'category',
      label: 'Te veel verzoeken (DoS)',
      collapsed: false,
      items: ['veiligheid/dos/zwakheid', 'veiligheid/dos/oplossing', 'veiligheid/dos/praktijk'],
    },
    {
      type: 'category',
      label: 'Wachtwoorden veilig opslaan',
      collapsed: false,
      items: [
        'veiligheid/wachtwoorden/zwakheid',
        'veiligheid/wachtwoorden/oplossing',
        'veiligheid/wachtwoorden/praktijk',
      ],
    },
  ],
};

export default sidebars;
