import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Handmatige sidebar, bewust niet autogenerated uit de mappenstructuur: de
// lessen groeperen in blokken zónder de bestanden te verplaatsen, want
// verplaatsen verandert de URL's — en die staan in honderden interne links en
// in bookmarks van leerlingen. Dit bestand is daarmee de enige bron van
// volgorde; de lesbestanden hebben geen sidebar_position meer.
//
// De cheatsheet en de troubleshooting-pagina staan bewust in geen enkele
// sidebar: het zijn referentiepagina's, bereikbaar via de navbar. Projectstructuur
// ook niet; die is naslag en gelinkt vanuit de cheatsheet en de lessen. In de
// navbar paste hij niet meer: op 1280 breed liepen de items dan over twee regels.
const sidebars: SidebarsConfig = {
  // Eerst de startpagina: wat je aan het eind hebt, wat je al moet kunnen, en
  // de route als kaart (<Routekaart>, die deze sidebar zelf leest). De navbar-
  // link FastAPI komt daar uit.
  apiSidebar: [
    'FastAPI/index',
    {
      type: 'category',
      label: 'Je eerste server',
      items: [
        'FastAPI/installatie',
        'FastAPI/eerste_endpoint',
        'FastAPI/verzoek-eerste',
        'FastAPI/devtools-netwerk',
      ],
    },
    {
      type: 'category',
      label: "HTML-pagina's",
      items: [
        'FastAPI/html_tonen',
        'FastAPI/html_bestanden',
        'FastAPI/links',
        'FastAPI/static_files',
        'FastAPI/afbeeldingen',
        'FastAPI/verzoek-static',
      ],
    },
    {
      type: 'category',
      label: 'Templates en formulieren',
      items: [
        'FastAPI/templates',
        'FastAPI/get_vs_post',
        'FastAPI/forms',
        'FastAPI/post_met_templates',
      ],
    },
    {
      type: 'category',
      label: 'Gegevens opslaan en tonen',
      items: [
        'FastAPI/database',
        'FastAPI/post_naar_database',
        'FastAPI/lijst_tonen',
        'FastAPI/redirect',
        'FastAPI/detailpagina',
        'FastAPI/verzoek-get',
      ],
    },
    {
      type: 'category',
      label: 'Uitbreiding: zonder herladen (htmx)',
      items: ['FastAPI/htmx', 'FastAPI/htmx-overzicht', 'FastAPI/verzoek-htmx'],
    },
    {
      type: 'category',
      label: 'Uitbreiding: JavaScript in de browser',
      items: ['FastAPI/javascript', 'FastAPI/devtools-console', 'FastAPI/server-of-browser'],
    },
    {
      type: 'category',
      label: 'Uitbreiding: onthouden (cookies en sessies)',
      items: [
        'FastAPI/cookies',
        'FastAPI/sessies',
        'FastAPI/cookie-of-sessie',
        'FastAPI/verzoek-sessie',
      ],
    },
    {
      type: 'category',
      label: 'Afronden',
      items: ['FastAPI/hoe-een-verzoek-werkt', 'FastAPI/laat-het-zien'],
    },
  ],
  // Eerst de startpagina (het ene idee, de spelregel, de statuscodes) en het
  // gereedschap (httpx). Dan per zwakheid een categorie met kleine lessen, van
  // makkelijk naar moeilijk: zichtbaar (wat je server laat zien, nog zonder
  // aanval), invoer, xss, dos, toegang, cookies, wachtwoorden.
  // DoS staat vroeg, want het is één decorator en een for-loop; Wachtwoorden
  // staat achteraan en gebruikt de limiet uit DoS. Ingeklapt, zodat de sidebar
  // een kaart blijft; Docusaurus klapt de reeks open waar de leerling in zit.
  veiligheidSidebar: [
    'veiligheid/index',
    'veiligheid/gereedschap',
    {
      type: 'category',
      label: 'Wat je server laat zien',
      collapsed: true,
      items: [
        'veiligheid/zichtbaar/handleiding',
        'veiligheid/zichtbaar/vergeten',
        'veiligheid/zichtbaar/uitzetten',
        'veiligheid/zichtbaar/bestanden',
        'veiligheid/zichtbaar/gitignore',
        'veiligheid/zichtbaar/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Invoer controleren',
      collapsed: true,
      items: [
        'veiligheid/invoer/maxlength',
        'veiligheid/invoer/grenzen',
        'veiligheid/invoer/fouten-lezen',
        'veiligheid/invoer/inhoud',
        'veiligheid/invoer/getallen',
        'veiligheid/invoer/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'HTML van een bezoeker (XSS)',
      collapsed: true,
      items: [
        'veiligheid/xss/zwakheid',
        'veiligheid/xss/escape',
        'veiligheid/xss/templates',
        'veiligheid/xss/safe',
        'veiligheid/xss/eigen-project',
        'veiligheid/xss/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Te veel verzoeken (DoS)',
      collapsed: true,
      items: [
        'veiligheid/dos/verzoek',
        'veiligheid/dos/dos-en-ddos',
        'veiligheid/dos/zelf-meten',
        'veiligheid/dos/limiet',
        'veiligheid/dos/te-veel',
        'veiligheid/dos/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Wie mag wat',
      collapsed: true,
      items: [
        'veiligheid/toegang/zwakheid',
        'veiligheid/toegang/controle',
        'veiligheid/toegang/server-weet',
        'veiligheid/toegang/elk-endpoint',
        'veiligheid/toegang/eigen-project',
        'veiligheid/toegang/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Cookies afschermen',
      collapsed: true,
      items: [
        'veiligheid/cookies/zwakheid',
        'veiligheid/cookies/httponly',
        'veiligheid/cookies/samesite',
        'veiligheid/cookies/uitloggen',
        'veiligheid/cookies/eigen-project',
        'veiligheid/cookies/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Wachtwoorden veilig opslaan',
      collapsed: true,
      items: [
        'veiligheid/wachtwoorden/gewone-tekst',
        'veiligheid/wachtwoorden/hash',
        'veiligheid/wachtwoorden/zout',
        'veiligheid/wachtwoorden/traag',
        'veiligheid/wachtwoorden/registreren',
        'veiligheid/wachtwoorden/inloggen',
        'veiligheid/wachtwoorden/wijzigen',
        'veiligheid/wachtwoorden/praktijk',
      ],
    },
    'veiligheid/eigen-project',
  ],
};

export default sidebars;
