import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Handmatige sidebar, bewust niet autogenerated uit de mappenstructuur: de
// lessen groeperen in zes blokken zónder de bestanden te verplaatsen, want
// verplaatsen verandert de URL's — en die staan in honderden interne links en
// in bookmarks van leerlingen. Dit bestand is daarmee de enige bron van
// volgorde; de lesbestanden hebben geen sidebar_position meer.
//
// De cheatsheet en de troubleshooting-pagina staan bewust in geen enkele
// sidebar: het zijn referentiepagina's, bereikbaar via de navbar.
const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: 'category',
      label: 'Starten',
      items: [
        'FastAPI/installatie',
        'FastAPI/eerste_endpoint',
        'FastAPI/verzoek-eerste',
        'FastAPI/devtools-netwerk',
      ],
    },
    {
      type: 'category',
      label: "Pagina's tonen",
      items: [
        'FastAPI/html_tonen',
        'FastAPI/static_files',
        'FastAPI/html_bestanden',
        'FastAPI/links',
        'FastAPI/afbeeldingen',
        'FastAPI/verzoek-static',
      ],
    },
    {
      type: 'category',
      label: 'Formulieren',
      items: ['FastAPI/get_vs_post', 'FastAPI/forms', 'FastAPI/post_met_templates'],
    },
    {
      type: 'category',
      label: 'Het gastenboek',
      items: [
        'FastAPI/database',
        'FastAPI/post_naar_database',
        'FastAPI/lijst_tonen',
        'FastAPI/redirect',
        'FastAPI/detailpagina',
        'FastAPI/verzoek-get',
        'FastAPI/verzoek-post',
      ],
    },
    {
      type: 'category',
      label: 'Zonder herladen',
      items: ['FastAPI/htmx', 'FastAPI/htmx-overzicht', 'FastAPI/verzoek-htmx'],
    },
    {
      type: 'category',
      label: 'In de browser',
      items: ['FastAPI/javascript', 'FastAPI/devtools-console', 'FastAPI/server-of-browser'],
    },
    {
      type: 'category',
      label: 'Onthouden',
      items: [
        'FastAPI/cookies',
        'FastAPI/sessies',
        'FastAPI/cookie-of-sessie',
        'FastAPI/verzoek-sessie',
      ],
    },
    {
      type: 'category',
      label: 'Afronden',
      items: [
        'FastAPI/hoe-een-verzoek-werkt',
        'FastAPI/laat-het-zien',
        'FastAPI/jouw-project',
        'FastAPI/projectstructuur',
      ],
    },
  ],
  // Eerst de startpagina (het ene idee, de spelregel, de statuscodes) en het
  // gereedschap (httpx). Dan per zwakheid een categorie met kleine lessen, van
  // dichtbij het eigen gastenboek naar ver weg: invoer, xss, toegang, cookies,
  // wachtwoorden, dos. Ingeklapt, zodat de sidebar een kaart blijft; Docusaurus
  // klapt de reeks open waar de leerling in zit.
  veiligheidSidebar: [
    'veiligheid/index',
    'veiligheid/gereedschap',
    {
      type: 'category',
      label: 'Invoer controleren',
      collapsed: true,
      items: [
        'veiligheid/invoer/maxlength',
        'veiligheid/invoer/grenzen',
        'veiligheid/invoer/fouten-lezen',
        'veiligheid/invoer/inhoud',
        'veiligheid/invoer/getallen',
        'veiligheid/invoer/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'HTML van een bezoeker (XSS)',
      collapsed: true,
      items: ['veiligheid/xss/zwakheid', 'veiligheid/xss/oplossing', 'veiligheid/xss/praktijk'],
    },
    {
      type: 'category',
      label: 'Wie mag wat',
      collapsed: true,
      items: [
        'veiligheid/toegang/zwakheid',
        'veiligheid/toegang/oplossing',
        'veiligheid/toegang/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Cookies afschermen',
      collapsed: true,
      items: [
        'veiligheid/cookies/zwakheid',
        'veiligheid/cookies/oplossing',
        'veiligheid/cookies/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Wachtwoorden veilig opslaan',
      collapsed: true,
      items: [
        'veiligheid/wachtwoorden/gewone-tekst',
        'veiligheid/wachtwoorden/hash',
        'veiligheid/wachtwoorden/zout',
        'veiligheid/wachtwoorden/traag',
        'veiligheid/wachtwoorden/registreren',
        'veiligheid/wachtwoorden/inloggen',
        'veiligheid/wachtwoorden/wijzigen',
        'veiligheid/wachtwoorden/praktijk',
      ],
    },
    {
      type: 'category',
      label: 'Te veel verzoeken (DoS)',
      collapsed: true,
      items: [
        'veiligheid/dos/verzoek',
        'veiligheid/dos/dos-en-ddos',
        'veiligheid/dos/zelf-meten',
        'veiligheid/dos/limiet',
        'veiligheid/dos/te-veel',
        'veiligheid/dos/praktijk',
      ],
    },
  ],
};

export default sidebars;
