import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * De sidebar wordt automatisch gegenereerd uit de mapstructuur in docs/.
 * De volgorde en labels komen uit de _category_.json bestanden.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
