// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Handmatige sidebar met drie moeilijkheidsgroepen: Beginner → Gevorderd →
 * Expert. De challenges staan in vaste mappen (01-…/), maar de sidebar-volgorde
 * komt hieruit, niet uit het mapnummer — zo staan de zwaarste (en meest
 * lokaal-afhankelijke) challenges onderaan zonder dat we mappen of URL's
 * hernoemen. Elke challenge wordt een inklapbare groep met zijn vier levels.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

/**
 * Eén challenge als inklapbare groep (Low/Medium/High/Impossible eronder).
 * @param {string} dir  mapnaam onder docs/dvwa_tutorial/
 * @param {string} label  weergavenaam (gelijk aan _category_.json)
 */
const challenge = (dir, label) => ({
  type: 'category',
  label,
  collapsed: true,
  items: [{ type: 'autogenerated', dirName: `dvwa_tutorial/${dir}` }],
});

const sidebars = {
  tutorialSidebar: [
    'dvwa_tutorial/index',
    {
      type: 'category',
      label: 'Voorbereiding',
      collapsed: false,
      items: ['installatie', 'dvwa_installatie', 'linux_leren', 'http_leren', 'sql_leren'],
    },
    {
      type: 'category',
      label: 'Beginner — volledig in de browser',
      collapsed: false,
      items: [
        challenge('02-command-injection', 'Command Injection'),
        challenge('03-authorization-bypass', 'Authorization Bypass'),
        challenge('06-xss-reflected', 'XSS (Reflected)'),
        challenge('04-sql-injection', 'SQL Injection'),
        challenge('10-file-inclusion', 'File Inclusion'),
        challenge('09-csrf', 'CSRF'),
      ],
    },
    {
      type: 'category',
      label: 'Gevorderd',
      collapsed: false,
      items: [
        challenge('05-sql-injection-blind', 'SQL Injection (Blind)'),
        challenge('07-xss-stored', 'XSS (Stored)'),
        challenge('12-weak-session-ids', 'Weak Session IDs'),
        challenge('11-file-upload', 'File Upload'),
        challenge('01-brute-force', 'Brute Force'),
      ],
    },
    {
      type: 'category',
      label: 'Expert — lokale installatie nodig',
      collapsed: false,
      items: [
        challenge('08-xss-dom', 'XSS (DOM)'),
        challenge('13-csp-bypass', 'CSP Bypass'),
        challenge('14-javascript-attacks', 'JavaScript Attacks'),
      ],
    },
    'dvwa_tutorial/word-de-developer',
    'cheatsheet',
  ],
};

export default sidebars;
