import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  installatieSidebar: [{type: 'autogenerated', dirName: 'installatie-vscode'}],
  webSidebar: [{type: 'autogenerated', dirName: 'web'}],
  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
  gitSidebar: [{type: 'autogenerated', dirName: 'git'}],
};

export default sidebars;
